# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Win32-MSAgent
version:      0.07
version_from: lib/Win32/MSAgent.pm
installdirs:  site
requires:
    File::Basename:                0
    File::Find::Rule:              0
    Win32::OLE:                    0
    Win32::SAPI4:                  0.03

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
